name: Push to Client Repository

on:
  push:
    branches:
      - main   # or whichever branch you want to trigger from

jobs:
  push-to-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # Important: don't use default GitHub token

      - name: Configure Git
        run: |
          git config --global user.name "Jaiwar SyncBot"
          git config --global user.email "jaiswar@users.noreply.github.com"

      - name: Clone Client Repository
        env:
          CLIENT_REPO_PAT: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          # Clone the client repo using the PAT
          git clone https://x-access-token:${CLIENT_REPO_PAT}@github.com/atharva-agi/atharva-cms.git

          # Copy files from the source repo to client repo (excluding .git folder)
          rsync -av --exclude='.git' ./ atharva-cms/

          cd atharva-cms

          git add .
          git commit -m "Sync from source repo to client repo" || echo "No changes to commit"
          git push origin main   # or whichever branch
