name: Push to Client Repository

on:
  push:
    branches:
      - main

jobs:
  push-to-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "Jaiwar SyncBot"
          git config --global user.email "jaiswar@users.noreply.github.com"

      - name: Clone Client Repository
        env:
          CLIENT_REPO_PAT: ${{ secrets.CLIENT_REPO_PAT }}
        run: |
          # Clone the client repo using the PAT
          git clone https://x-access-token:${CLIENT_REPO_PAT}@github.com/atharva-agi/atharva-cms.git

          # Sync source files to client repo, excluding .git and GitHub Actions workflows
          rsync -av --exclude='.git' --exclude='.github' ./ atharva-cms/

          cd atharva-cms

          git add .
          git commit -m "Sync from source repo to client repo" || echo "No changes to commit"
          git push origin main
